alertmanager:
  enabled: false

grafana:
  plugins:
  - grafana-piechart-panel
  - grafana-worldmap-panel
  
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - grafana.simplyzee.dev
    tls:
      - secretName: grafana-sz-tls
        hosts:
          - grafana.simplyzee.dev

prometheusSpec:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
