apiVersion: v1
kind: Endpoints
metadata:
  name: speedtest-metrics
  namespace: monitoring
  labels:
    k8s-app: speedtest-metrics
subsets:
- addresses:
  - ip: 82.129.119.242
  ports:
  - name: metrics
    port: 9112
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-metrics
  namespace: monitoring
  labels:
    k8s-app: speedtest-metrics
spec:
  type: ExternalName
  externalName: 82.129.119.242
  ports:
  - name: metrics
    port: 9112
    protocol: TCP
    targetPort: 9112
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: speedtest-metrics
  namespace: monitoring
  labels:
    k8s-app: speedtest-metrics
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      k8s-app: speedtest-metrics
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: metrics
    interval: 60s
    path: /metrics
    honorLabels: true
    scrapeTimeout: 60s
