apiVersion: apps/v1
kind: Deployment
metadata:
  name: varken
  namespace: varken
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varken
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: varken
    spec:
      hostname: varken
      restartPolicy: Always
      containers:
      - name: varken
        image: boerderij/varken:develop
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: varken-env
        volumeMounts:
          - mountPath: /config
            name: config
      volumes:
        - name: config
          hostPath:
            path: /opt/varken/
